### PR TITLE
feat: centered urlbar with full screen overlay for wide screen

### PR DESCRIPTION
**Pull request by c3t1nn**
feat: Centered urlbar with full screen overlay

Description:
This PR improves the urlbar experience by:
- Centering the urlbar popup when extended
- Adding a full screen overlay for better focus
- Using Firefox's native colors for consistent theming
- Improving visibility with darkened background

Changes:
- Modified urlbar positioning to be centered
- Added full screen overlay with native Firefox colors
- Improved transitions for smooth animations
- Fixed z-index issues for proper layering

Screenshots:
resim

### CODE REVIEW

**Comment by nuclearcodecat** [comment]
thanks for the pr. i'll take a look asap :P. i'd really appreciate if the comments were english

**Comment by c3t1nn** [comment]
> thanks for the pr. i'll take a look asap :P. i'd really appreciate if the comments were english

you are right! sorry it was late night, dont know what was I thinking. I have updated pr. now its all english)

**Comment by c3t1nn** [comment]
I have made all corners round to make design more continius. I really liked your way of understanding this project, good work! 
resim

**Comment by nuclearcodecat** [comment]
the rounded corners were disabled on the right edge on purpose. i guess it could be added as an optional feature, but i don't really see it

**Comment by nuclearcodecat** [comment]
i'm sorry, i don't really like your changes. i could add the the code that centers the urlbar, that's very nice. i don't like the rounded corners and color changes you made. also something broke and native tabs don't work, there's a large amount of empty space on the right of winctr buttons

**Pull request closed without merging**
